
name: Built and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.9
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Projec1
      run: dotnet test TestProject1 --no-build --verbosity normal
    - name: Test Project2
      run: dotnet test TestProject2 --no-build --verbosity normal
    - name: Test Project3
      run: dotnet test TestProject3 --no-build --verbosity normal
      
